### ISSUE TITLE
Następne Spotkanie - Listopad 2015

### ISSUE THREAD

**Issue by afronski** [silesian-beamers/organization#1]
Potencjalne terminy następnego spotkania:

- 04.11 (*środa*)
- 06.11 (*piątek*)
- 09.11 (*poniedziałek*)
- 16.11 (*poniedziałek*)
- 18.11 (*środa*)

Głosujemy w komentarzach dając :+1: i określoną datę.

**Comment by mniec** [comment]
Dla mnie wszystkie są dobre po za 9.11.

**Comment by MLaszczewski** [comment]
Dla mnie wszystkie są dobre

**Comment by mentero** [comment]
Zapomniałeś o :+1:  :) Dla mnie wszystko poza 06.11

**Comment by stronger** [comment]
Dla mnie piątek, ew. każdy dzień po godzinie 20-tej.

**Comment by mbSmaga** [comment]
Wszystko tylko nie poniedziałki :-1:

**Comment by krzyzol** [comment]
Dla mnie wszystkie ok poza 04.11

**Comment by frakti** [comment]
j.w. wszystko poza 4.11.

**Comment by michalmuskala** [comment]
Mi również pasują wszystkie podane terminy

**Comment by afronski** [comment]
Proponuję 18.11 (pomijam pierwsze dwa tygodnie ze względu na 01.11 i 11.11, no i poniedziałki odpadają :wink:).

@mniec @MLaszczewski Czy ten termin Wam pasuje jeśli chodzi o prezentacje?

**Comment by mniec** [comment]
Termin mi pasuje :+1

**Comment by MLaszczewski** [comment]
Mi też pasuje.

**Comment by afronski** [comment]
Okej, tak więc data następnego spotkania to 18.11.
Aktualizuję stronę i przygotowuję spotkanie na meet-up (wrzucę oba linki do repozytorium).
