### ISSUE TITLE
Tematyka warsztatów - Elixir + Phoenix

### ISSUE THREAD

**Issue by afronski** [silesian-beamers/organization#10]
@michalmuskala @mentero Propozycje tematów na całodniowe warsztaty:

- Chat
- Blog
- Coś na kształt: https://github.com/afronski/wolves-and-rabbits-world-simulation-ui i https://github.com/afronski/wolves-and-rabbits-world-simulation

**Comment by michalmuskala** [comment]
Ostatnia propozycja jest o tyle ciekawa, że pozwala na pokazanie siły OTP i projektowania aplikacji w oparciu o OPT. Myślę, że coś podobnego, ale prostszego, mogło by być ciekawe.

**Comment by afronski** [comment]
@michalmuskala Zgadzam się, ale wymaga tego, żeby ew. też pokazać coś poza Elixirem (no bo JSa też trzeba napisać). Mnie się sam pomysł bardzo podoba, pytanie jak bardzo go podciągniemy pod Elixir + OTP.

@mentero co myślisz o tych propozycjach?

**Comment by mentero** [comment]
A może coś w stylu `phoenix-trello`? Można zacząć od bardziej statycznej wersji i dodawać powoli JSy

**Comment by afronski** [comment]
Wygrał *Interaktywny Tetris*.
