### ISSUE TITLE
Prezentacja ze świata RTB i Erlanga

### ISSUE THREAD

**Issue by mniec** [silesian-beamers/organization#2]
Proponuje poniższe 3 tematy

1. Architektura systemu do RTB w Erlangu
2. Erlang Term Storage
3. Erlang Tracing

**Comment by mentero** [comment]
Bardzo chętnie posłucham o 1 i 2

**Comment by afronski** [comment]
:+1: na temat nr 1

**Comment by michalmuskala** [comment]
Wszystkie trzy tematy są ciekawe, ale myślę, że najciekawszy byłby 1.

**Comment by afronski** [comment]
@mniec Ogłosiłem temat nr 1: http://www.meetup.com/Silesian-BEAMers/events/226035167/ :wink:
