### ISSUE TITLE
Prezentacja: Zastosowanie Elixira w tworzeniu aplikacji webowych czasu rzeczywistego

### ISSUE THREAD

**Issue by MLaszczewski** [silesian-beamers/organization#3]
Na przykładzie aplikacji gry mmo lub chata omówię metody tworzenia aplikacji webowych czasu rzeczywistego.

**Comment by mentero** [comment]
:+1:

**Comment by mbSmaga** [comment]
Jestem bardzo na :+1: czekam na prezentacje ;)

**Comment by afronski** [comment]
@MLaszczewski ogłosiłem temat: http://www.meetup.com/Silesian-BEAMers/events/226035167/
