### ISSUE TITLE
Następne Spotkanie - Luty 2016

### ISSUE THREAD

**Issue by afronski** [silesian-beamers/organization#6]
Potencjalne terminy następnego spotkania zawarłem w ankiecie.
Głosowanie: http://doodle.com/poll/vqarscna42czvira#table

**Comment by afronski** [comment]
Wygrywa termin 08.02 - 18:00.

**Comment by LGLO** [comment]
To można przekleić na meetup'a

Frege - początki.
45 minut, przez które tworząc webservice a'la jsonlint.com postaram się:
- przedstawić kluczowe cechy języka
- przedstawić albo nazwać przydatne narzędzia (ekosystem)
- skomentować bieżącą sytuację community i projektu

To jest pierwsze publiczne przesłuchanie przed prezentacją na LambdaDays, ale będzie po polsku.
