### ISSUE TITLE
Całodniowe warsztaty - Elixir + Phoenix

### ISSUE THREAD

**Issue by afronski** [silesian-beamers/organization#8]
Pytanie do Was - kto byłby zainteresowany całodniowymi warsztatami z tematyki Elixir + Phoenix?
Jeśli ktoś jest zainteresowany proszę o :+1: w komentarzu. 

- *Termin*: kwietniowa sobota, konkretny termin wybierzemy poniższą ankietą:
  - http://doodle.com/poll/ehuexyu62aw79h5m
- *Miejsce*: Hackerspace Silesia
- *Czas trwania*: 8h (*z przerwami*)

**Comment by jsynowiec** [comment]
:+1:

**Comment by szimek** [comment]
:+1:

**Comment by kapke** [comment]
:+1:

**Comment by firemark** [comment]
:+1:

**Comment by LGLO** [comment]
+1 (nie gwarantuję, że przyjdę, bo to sobota...)

**Comment by mentero** [comment]
:+1:

**Comment by michalpipa** [comment]
:+1:

**Comment by michalmuskala** [comment]
:+1:

**Comment by mbSmaga** [comment]
:+1:

**Comment by afronski** [comment]
@jsynowiec @szimek @kapke @firemark @LGLO @mentero @michalpipa @michalmuskala @mbSmaga Ankieta z terminami: http://doodle.com/poll/ehuexyu62aw79h5m

**Comment by tarnas14** [comment]
:+1:

**Comment by tarnas14** [comment]
i jeszcze: jest tu napisane 'Termin: sobota w Marcu (2016, konkretny termin wybierzemy ankietą)', a na fb i w doodle'u jest kwiecień :D

**Comment by alucardo** [comment]
:+1:

**Comment by KamilLelonek** [comment]
:+1: byłbym

**Comment by mariuswol** [comment]
:+1:

**Comment by fabiankrol** [comment]
:+1:

**Comment by p-janik** [comment]
:+1:

**Comment by panadash** [comment]
:+1:

**Comment by panadash** [comment]
:+1:

**Comment by panadash** [comment]
:+1:

**Comment by karolgorecki** [comment]
:+1:

**Comment by jgautheron** [comment]
:+1:

**Comment by ccompoi** [comment]
:+1:

**Comment by afronski** [comment]
Wygrywa termin 09.04, godzina 9:00.
